spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 961120
    url: jdbc:mysql://localhost:3306/debate_mall?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
server:
  servlet:
    context-path: /rebatemall
ftp:
  ip: 127.0.0.1
  port: 21
  username: zhr
  password: 961120
  filepath: /